### ISSUE TITLE
Instructor Feedback

### ISSUE THREAD

**Issue by droxey** [PhyllisWong/Inspiration-Station#2]
Beautiful deliverable, @PhyllisWong!

There are a few requirements you missed in order to pass the project. Could you please add these by EOD tomorrow and close this ticket to signal completion?

* CRUD >=2 Resources and associate them (only one resource w/ no associations)
* 100% test coverage of all routes (0 test coverage)
* A conventional UI using Bootstrap 4 (bootstrap 3.3.7 linked in `main.handlebars`)

Thanks!
-d

**Comment by phylliswong** [comment]
- [x] Bootstrap linked in a head.hbs partial
- [x] Will add test coverage & second resource

**Comment by droxey** [comment]
Great work! This is now passing 👍

**Comment by phylliswong** [comment]
Thanks Dani, woohoo!
